### ISSUE TITLE
WordPress Version Detection

### ISSUE THREAD

**Issue by JamesHabben** [Tuhinshubhra/CMSeeK#10]
I tested this tool against my blog at https-4n6ir-com and CMSeeK isn't able to detect the wp version. I ran wpscan against the same, and it detected a version 'identified from advanced fingerprinting'.

**Comment by JamesHabben** [comment]
side note: CMSeeK identified 2 users, while wpscan identified only 1.

**Comment by Tuhinshubhra** [comment]
Hi thanks for the info I will look into it and add a detection method if possible.

**Comment by Tuhinshubhra** [comment]
I just checked the site and it seems to be hosted on wordpress.com, CMSeeK's WordPress scan is meant for wordpress.ORG (self hosted) sites... 

Closing issue and thanks for the feedback I will add some stuffs for wordpress.com hosted sites in the upcoming version!

P.S - wordpress.COM and wordpress.ORG are two separate entities although they share the same name.
