### ISSUE TITLE
[SUGGESTION] CMS detction failed!

### ISSUE THREAD

**Issue by tuhin1729** [Tuhinshubhra/CMSeeK#102]
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/62632413/81609109-ccfa8800-93c6-11ea-84c2-160317edf112.png)
- CMSeeK Version: 1.1.2
    - Target: https://thecyberagents.com/
    - Probable CMS: <name and/or cms url>

**Comment by Tuhinshubhra** [comment]
Do you know what CMS the site is using?

**Comment by Tuhinshubhra** [comment]
Closing issue. Make sure you include the necessary details when you create an issue next time.
