### ISSUE TITLE
No such file or directory: 'wordlist/passwords.txt'

### ISSUE THREAD

**Issue by odion-cloud** [Tuhinshubhra/CMSeeK#117]
this is the error i get

  File "C:\Users\USER\Desktop\CMSeeK-master\cmseek.py", line 279, in <module>
    cms_brute()
  File "C:\Users\USER\Desktop\CMSeeK-master\cmsbrute\wp.py", line 69, in start
    pwd_file = open("wordlist/passwords.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'wordlist/passwords.txt'

**Comment by Youssefhart88** [comment]
python3 wordlister.py
usage: wordlister.py [-h] --input INPUT --output OUTPUT --perm PERM --min MIN --max MAX [--leet] [--cap] [--up] [--append APPEND] [--prepend PREPEND] [--sort]
wordlister.py: error: the following arguments are required: --input, --output, --perm, --min, --max
