### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by vulnz** [Tuhinshubhra/CMSeeK#12]
bro, hello.
nice product.
i tested on opencart - seems it does not work.
where to add key from wpvulndb?

**Comment by Tuhinshubhra** [comment]
Hi,
1. About the opencart thing can you provide me with the target url so i could check
2. You don't need to add any wpvuldb key

**Comment by Tuhinshubhra** [comment]
closing the issue... reopen with all the necessary information!
