### ISSUE TITLE
[SUGGESTION] CMS detction failed! Roundcube Webmail 

### ISSUE THREAD

**Issue by Yneth** [Tuhinshubhra/CMSeeK#134]
- CMSeeK Version: 1.1.3
    - Target: https://62.148.133.85/
    - Probable CMS: Roundcube Webmail     (IMAP client)

**Comment by h4ckzard** [comment]
To be fixed in https://github.com/Tuhinshubhra/CMSeeK/pull/168

**Comment by Tuhinshubhra** [comment]
Fixed! Thanks @h4ckzard & @Yneth
