### ISSUE TITLE
[SUGGESTION] CMS detction failed!

### ISSUE THREAD

**Issue by acidtmn** [Tuhinshubhra/CMSeeK#138]
- CMSeeK Version: 1.1.3
- Target: https://dle-news.ru/
- Probable CMS: Datalife Engine

**Comment by h4ckzard** [comment]
To be fixed in https://github.com/Tuhinshubhra/CMSeeK/pull/168

**Comment by Tuhinshubhra** [comment]
Fixed! Thanks @h4ckzard & @acidtmn
