### ISSUE TITLE
How about adding found username to password.txt automatically?

### ISSUE THREAD

**Issue by evolnasus** [Tuhinshubhra/CMSeeK#14]
How about adding found username to password.txt automatically? It will be of great help!
![image](https://user-images.githubusercontent.com/38310930/42746105-d86aaf96-8908-11e8-878c-89e6f8d95f3d.png)

**Comment by Tuhinshubhra** [comment]
it saves bruteforce results as well.. check your Result/<target> directory, you'll find a txt file and the result will be somewhat like this:

```
### CMSeeK Bruteforce Result


Site: <website url>
Login URL: <login url>
Username: <user>
Password: <pass>
```

**Comment by Tuhinshubhra** [comment]
also the link to the text file is showed after successful bruteforce 

![selection_027](https://user-images.githubusercontent.com/28696468/42764850-48531f16-8934-11e8-8adb-47a0cbffd292.png)

**Comment by Tuhinshubhra** [comment]
closing the issue for now, feel free to open for any other problem.. also please follow the proper structure before creating issue.

https://github.com/Tuhinshubhra/CMSeeK#opening-issue

**Comment by evolnasus** [comment]
Well, what I mean is when program is procceding [3]    Bruteforce CMSs option, why not adding found username（zhangkai） to password.txt automatically? 
![image](https://user-images.githubusercontent.com/38310930/42765856-8a3be1a8-894b-11e8-8f60-112bc8c33893.png)

**Comment by Tuhinshubhra** [comment]
ahh well that's a good suggestion... will add it in the next version... thanks for your input

**Comment by Tuhinshubhra** [comment]
Feature added! update to the latest version. Thank you!
