### ISSUE TITLE
Error in scanning

### ISSUE THREAD

**Issue by iamtatai14** [Tuhinshubhra/CMSeeK#141]
I am not able to function the scan with CMSeeK 
![Screenshot_2022-05-19-23-14-39-324_com termux](https://user-images.githubusercontent.com/105880387/169364200-807fb56b-1141-41d1-875e-a1e6e8a1ca97.jpg)
Plz reply

**Comment by Tuhinshubhra** [comment]
It's not an error, it just couldn't detect any CMS.
