### ISSUE TITLE
[SUGGESTION] CMS detction failed!

### ISSUE THREAD

**Issue by Edgaras7** [Tuhinshubhra/CMSeeK#145]
- CMSeeK Version: 1.1.3
- Target: https://stickizi.com/
- Probable CMS: Zyro / zyro.com

**Comment by Edgaras7** [comment]
Few more examples:

https://muistore.eu/
https://www.wildflowcreate.com/
https://homejazz.lt/

**Comment by h4ckzard** [comment]
To be fixed in https://github.com/Tuhinshubhra/CMSeeK/pull/168

**Comment by Tuhinshubhra** [comment]
Fixed! Thanks @h4ckzard & @Edgaras7
