### ISSUE TITLE
[SUGGESTION] CMS detction failed!

### ISSUE THREAD

**Issue by Edgaras7** [Tuhinshubhra/CMSeeK#146]
- CMSeeK Version: 1.1.3
- Target: https://www.panorama.lt/
- Probable CMS: SilverStripe CMS / https://www.silverstripe.org/

**Comment by h4ckzard** [comment]
https://github.com/Tuhinshubhra/CMSeeK/pull/168

**Comment by Tuhinshubhra** [comment]
Fixed! Thanks @h4ckzard & @Edgaras7
