### ISSUE TITLE
[SUGGESTION] CMS detction failed!

### ISSUE THREAD

**Issue by lengers** [Tuhinshubhra/CMSeeK#15]
- CMSeeK Version: 1.0.6
- Target: https://www.klein.wine/typo3/
- Probable CMS: TYPO3, should normaly be found at <domain>/typo3

**Comment by Tuhinshubhra** [comment]
Fixed! please update your version of CMSeeK.
Thanks for reporting tho.. looks like I did a typo spelling "typo3" lol,

Closing issue now, feel free to open a new one at any time to help CMSeeK get better!
