### ISSUE TITLE
[SUGGESTION] CMS detection failed! Squarespace

### ISSUE THREAD

**Issue by hellodarkness** [Tuhinshubhra/CMSeeK#163]
CMSeeK Version: 1.1.3
    Target: https://www.forgegrappling.com/
    Probable CMS: Squarespace site builder / https://www.squarespace.com/

**Comment by hellodarkness** [comment]
I think I pasted the wrong example site here but I've made a PR with some better examples #166

**Comment by Tuhinshubhra** [comment]
Thank you ^_^ 
Merged the pr, closing this issue as fixed (thanks again)!
