### ISSUE TITLE
[SUGGESTION] CMS detection failed!

### ISSUE THREAD

**Issue by hellodarkness** [Tuhinshubhra/CMSeeK#164]
CMSeeK Version: 1.1.3
Target: https://filipematosbjj.com/
Probable CMS:  Zyro Website Builder - https://zyro.com/

**Comment by h4ckzard** [comment]
To be fixed in https://github.com/Tuhinshubhra/CMSeeK/pull/168

**Comment by Tuhinshubhra** [comment]
Fixed! Thanks @h4ckzard & @hellodarkness
