### ISSUE TITLE
[x] robots.txt not found or empty! [x] Unable to detect CMS even by directory (modules) checks!

### ISSUE THREAD

**Issue by lebrons111** [Tuhinshubhra/CMSeeK#189]
[x] robots.txt not found or empty!
[x] Unable to detect CMS even by directory (modules) checks!

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
