### ISSUE TITLE
Detect SharePoint

### ISSUE THREAD

**Issue by daniel2005d** [Tuhinshubhra/CMSeeK#19]
Hi

I Consider include SharePoint in CMS detection. The method is verify the URL

/_layouts/authenticate.aspx
/_catalogs/wp

Or

https://www.fpweb.net/sharepoint-blog/your-sharepoint-url-list-an-administrators-guid/.

**Comment by Tuhinshubhra** [comment]
can you provide me with some targets?

**Comment by Tuhinshubhra** [comment]
Added, update your version of CMSeeK
