### ISSUE TITLE
PHP-Nuke

### ISSUE THREAD

**Issue by ScriptTiger** [Tuhinshubhra/CMSeeK#22]
PHP-Nuke is an older CMS that is no longer in development, but plenty of websites still use it and it's still listed as an option in website install helpers like [Softaculous](https://www.softaculous.com/apps/cms/PHP-Nuke) and promoted by popular hosts like [SiteGround](https://www.siteground.com/php-nuke-hosting.htm). Obviously it's a terrible CMS to use in modern times, but it's still alive and unwell.

For a list of target websites:
https://trends.builtwith.com/websitelist/PHP-Nuke

**Comment by Tuhinshubhra** [comment]
Added detection for PHP Nuke, please update your version of CMSeeK, also thanks for the suggestion; it helps CMSeeK grow :)
