### ISSUE TITLE
phpBB

### ISSUE THREAD

**Issue by ScriptTiger** [Tuhinshubhra/CMSeeK#23]
By some definitions phpBB may not technically be a CMS out of the box, but plenty of people use it as one and it is certainly at least a user-generated content management system. It's an extremely popular forum platform and is categorized as a CMS by [Open Source CMS](https://www.opensourcecms.com/phpbb/). Virtually every website builder/install helper comes with packages for it. Many times it is placed in the subdirectory, such as `www.example.com/forum`, but it is also often placed in a subdomain of its own, such as `forum.example.com`.

Some target websites:
https://forums.veeam.com/
http://forum.vfb.de/
https://bb.steelguitarforum.com/
http://www.ultimatebootcd.com/forums/
https://www.reactos.org/forum/

**Comment by Tuhinshubhra** [comment]
Hey, thanks for the suggestion i am planning to add the forum softwares once i'm done adding all the CMSs so expect it added in the next release :)

**Comment by Tuhinshubhra** [comment]
Detection added for phpBB, please update your version of CMSeeK
