### ISSUE TITLE
UnboundLocalError: local variable 'joomcnf' referenced before assignment

### ISSUE THREAD

**Issue by Twibow** [Tuhinshubhra/CMSeeK#24]
Hello,

I'm having an error with the Bruteforce Module.
Please find the trace of this issue : 

> 
> [i] Checking for Joomla
> Traceback (most recent call last):
>   File "cmseek.py", line 185, in <module>
>     cms_brute()
>   File "/newtools/CMSeeK/cmsbrute/joom.py", line 97, in start
>     if joomcnf != '1':
> UnboundLocalError: local variable 'joomcnf' referenced before assignment

I take this opportunity to congratulate you for this work 👍

**Comment by Tuhinshubhra** [comment]
Hi i have applied a possible fix can you try and confirm? and thanks man :)

**Comment by Tuhinshubhra** [comment]
Assuming fixed, reopen issue if not.
