### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by soupnatzi** [Tuhinshubhra/CMSeeK#26]
[*] CMS Detected, CMS ID: wp, Detection method: header
[*] 2 Usernames were enumerated
[!] Skipping version vulnerability scan as WordPress Version wasn't detected
Traceback (most recent call last):
  File "cmseek.py", line 118, in <module>
    core.main_proc(site,cua)
  File "/root/Desktop/newtools/CMSeeK/cmseekdb/core.py", line 107, in main_proc
    advanced.start(cms, site, cua, ga, scode, ga_content)
  File "/root/Desktop/newtools/CMSeeK/deepscans/core.py", line 10, in start
    wpscan.start(id, url, ua, ga, source)
  File "/root/Desktop/newtools/CMSeeK/deepscans/wp/init.py", line 101, in start
    vulnss = len(result['vulnerabilities'])
TypeError: string indices must be integers

**Comment by Tuhinshubhra** [comment]
I have pushed a fix for the issue can you confirm?

**Comment by soupnatzi** [comment]
[i] Scanning Site: 
[i] Target redirected to: 
[#] Set  (y/n): y
[*] CMS Detected, CMS ID: wp, Detection method: header
[*] Path disclosure detected, path: 
[i] Checking user registration status
[i] Starting passive plugin enumeration
[*] 5 Plugins enumerated!
[i] Starting passive theme enumeration
[*] 2 themes detected!
[i] Starting Username Harvest
[i] Harvesting usernames from wp-json api
[*] Found user from wp-json : 
[*] Found user from wp-json : 
[i] Harvesting usernames from jetpack public api
[!] No results from jetpack api... maybe the site doesn't use jetpack
[i] Harvesting usernames from wordpress author Parameter
[*] 2 Usernames were enumerated
[!] Skipping version vulnerability scan as WordPress Version wasn't detected
Traceback (most recent call last):
  File "cmseek.py", line 118, in <module>
    core.main_proc(site,cua)
  File "/root/Desktop/newtools/CMSeeK/cmseekdb/core.py", line 107, in main_proc
    advanced.start(cms, site, cua, ga, scode, ga_content)
  File "/root/Desktop/newtools/CMSeeK/deepscans/core.py", line 10, in start
    wpscan.start(id, url, ua, ga, source)
  File "/root/Desktop/newtools/CMSeeK/deepscans/wp/init.py", line 101, in start
    vulnss = len(result['vulnerabilities'])
TypeError: string indices must be integers

same issue

**Comment by Tuhinshubhra** [comment]
I have fixed the issue.. please update cmseek

**Comment by soupnatzi** [comment]
[+]  Update Menu  [+] 
[i] Checking for updates
[i] CMSeeK Version: 1.0.9
[*] Latest Version: 1.0.9


[✔] CMSeeK is up to date, Thanks for checking update tho.. It's a good practise

 CMSeeK says ~ auf Wiedersehen
updated cmseek

[i] Scanning Site: 
[i] Target redirected to: 
[#] Set as target? (y/n): y
[*] CMS Detected, CMS ID: wp, Detection method: header
[*] Path disclosure detected, path: 
[i] Checking user registration status
[i] Starting passive plugin enumeration
[*] 5 Plugins enumerated!
[i] Starting passive theme enumeration
[*] 2 themes detected!
[i] Starting Username Harvest
[i] Harvesting usernames from wp-json api
[*] Found user from wp-json : 
[*] Found user from wp-json :
[i] Harvesting usernames from jetpack public api
[!] No results from jetpack api... maybe the site doesn't use jetpack
[i] Harvesting usernames from wordpress author Parameter
[*] Found user from redirection: 
[*] 2 Usernames were enumerated
[!] Skipping version vulnerability scan as WordPress Version wasn't detected
Traceback (most recent call last):
  File "cmseek.py", line 118, in <module>
    core.main_proc(site,cua)
  File "/root/Desktop/newtools/CMSeeK/cmseekdb/core.py", line 107, in main_proc
    advanced.start(cms, site, cua, ga, scode, ga_content)
  File "/root/Desktop/newtools/CMSeeK/deepscans/core.py", line 10, in start
    wpscan.start(id, url, ua, ga, source)
  File "/root/Desktop/newtools/CMSeeK/deepscans/wp/init.py", line 101, in start
    vulnss = len(result['vulnerabilities'])
TypeError: string indices must be integers

just checked updated cmseek and ran cmseek and still the same issue
root@:~# uname -a
Linux 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux

**Comment by Tuhinshubhra** [comment]
run the command `git pull`

**Comment by Tuhinshubhra** [comment]
Or do a fresh install.. remove everything and run `git clone https://github.com/Tuhinshubhra/CMSeeK`

**Comment by ScriptTiger** [comment]
Or just download the master ZIP real quick for testing purposes:
https://github.com/Tuhinshubhra/CMSeeK/archive/master.zip

**Comment by soupnatzi** [comment]
will do and let you know how it goes

**Comment by soupnatzi** [comment]
issue fixed fresh install worked.

**Comment by Tuhinshubhra** [comment]
Cool.. closing the issue.
