### ISSUE TITLE
CMSeek showing error 

### ISSUE THREAD

**Issue by venkatasidhartha** [Tuhinshubhra/CMSeeK#27]
[x] CMS Detection failed, if you know the cms please help me improve CMSeeK by reporting the cms along with the target by creating an issue

**Comment by ScriptTiger** [comment]
Target URL?

**Comment by Tuhinshubhra** [comment]
Fill these to actually help me here..

Target:
CMSeeK Version:
CMS:

**Comment by Tuhinshubhra** [comment]
Reopen with enough details, closing issue.
