### ISSUE TITLE
Drupal json output

### ISSUE THREAD

**Issue by Nic062** [Tuhinshubhra/CMSeeK#28]
Hello, 

I think's i have find a issue : 

`python3 cmseek.py -u drupal.com -r`

> ____

 [+]  CMS Scan Results  [+] 

 ┏━Target: www.drupal.com
 ┃
 ┠── CMS: Drupal
 ┃    │
 ┃    ├── Version: 8
 ┃    ╰── URL: https://drupal.org
 ┃
 ┠── Result: /home/user/CMSeeK/Result/drupal.com/cms.json
 ┃
 ┗━Scan Completed in 2.16 Seconds, using 2 Requests
> ____

`cat /home/user/CMSeeK/Result/drupal.com/cms.json`

Output : 
`{
    "cms_id": "dru",
    "cms_name": "",
    "cms_url": "",
    "detection_param": "header",
    "last_scanned": "2018-08-27 12:38:12.692850",
    "url": "http://drupal.com/"
}`

As you can see "cms_name" and "cms_url" is empty.

**Comment by Tuhinshubhra** [comment]
Hi, thanks for reporting the issue. I have pushed a fix please update your CMSeeK and confirm if it's fixed :)

**Comment by Tuhinshubhra** [comment]
Confirmed fix.. Closing the issue!

**Comment by Nic062** [comment]
Works perfectly, thanks !
