### ISSUE TITLE
Error: <urlopen error [Errno -2] Name or service not known>

### ISSUE THREAD

**Issue by MaximAndreev1011** [Tuhinshubhra/CMSeeK#30]
Linux parrot 4.17.0-parrot8-amd64 #1 SMP Parrot 4.17.8-1parrot8 (2018-08-11) x86_64 GNU/Linux

┌─[max@parrot]─[~/Desktop/new/CMSeeK]
└──╼ $python3 cmseek.py -l sites.txt

____ _  _ ____ ____ ____ _  _
|    |\/| [__  |___ |___ |_/  by @r3dhax0r
|___ |  | ___| |___ |___ | \_ Version 1.1.0 ForumZ

 [+]  CMS Detection And Deep Scan  [+] 

[i] Scanning Site: http://avtofiltry-shop.ruavto-finam.ruavtofinam.ruavtofinance24.ruavtofinance48.ruavto-finance.ruavtofinance.ruavtofinans116.ruavtofinans24.ruavtofinans31.ruavto-finans.ruavtofinans.ruavto-fina.ruavtofind.ruavtofininvest.ruavtofin.ruavtofint.ru
[x] Aborting CMSeek! Couldn't connect to site 
    Error: <urlopen error [Errno -2] Name or service not known>

	Press [ENTER] to continue

[✔] Finished Scanning all targets.. result has been saved under respective target directories

CMSeeK says ~ sayonara
┌─[max@parrot]─[~/Desktop/new/CMSeeK]
└──╼ $

P.S.: file sites.txt:
avtofiltry-shop.ru
avto-finam.ru
avtofinam.ru
avtofinance24.ru
avtofinance48.ru
avto-finance.ru
avtofinance.ru
avtofinans116.ru
avtofinans24.ru
avtofinans31.ru

P.P.S python3 cmseek.py -u example.com  <------ performs excellently!

**Comment by Tuhinshubhra** [comment]
the site list must pe comma `,` separated not new line.

**Comment by Tuhinshubhra** [comment]
Closing issue feel free to reopen if you find any other problems
