### ISSUE TITLE
[Suggestion] Return result in JSON

### ISSUE THREAD

**Issue by mzulfahmy** [Tuhinshubhra/CMSeeK#34]
Hi, 

Just some suggestion, let say i'm calling cmsseek.scan(domain) and it will return in json format.

Example :  
```
from cmseek import scan

cmseek.scan(domain)
return json
```

There is any idea for this enhancement?

Thanks

**Comment by Tuhinshubhra** [comment]
i have plans for this but not for now.. i will add it once I've added almost all cmss
