### ISSUE TITLE
Can't Scan target

### ISSUE THREAD

**Issue by rave991** [Tuhinshubhra/CMSeeK#38]
https://github.com/Tuhinshubhra/CMSeeK/issues/new

**Comment by ScriptTiger** [comment]
@rave991, I think you may have tried to copy the URL from another tab in your Web browser to paste it here but accidentally copied the URL of the same tab. Can you edit your issue and replace the current URL with the correct target URL?

**Comment by Tuhinshubhra** [comment]
Please provide a valid target, closing the issue as of now.. @ScriptTiger thanks for moderating the issues tho mate.. appreciate it.
