### ISSUE TITLE
[SUGGESTION] CMS detection failed! (orkis)

### ISSUE THREAD

**Issue by securiteinfo** [Tuhinshubhra/CMSeeK#44]
- CMSeeK Version: 1.1.0
- Target: [private]
CMS is ORKIS Ajaris Websuite (http://www.orkis.com/)

How to detect :
The web page contains :
<meta name="author" content="ORKIS SA">
<meta property="ajaris:baseURL" 
<meta property="ajaris:language"

**Comment by Tuhinshubhra** [comment]
Detection added for Orkis Ajaris Websuite, please clone the latest version of CMSeeK
