### ISSUE TITLE
Request: Remove re-direction confirmation prompt

### ISSUE THREAD

**Issue by smicallef** [Tuhinshubhra/CMSeeK#46]
I would love to write a module for SpiderFoot to use CMSeeK, but to do that it should be able to run CMSeeK from the command line in a completely hands-off way. Right now, if I run `cmseek.py example.com`, I will get prompted if it's the URL I want to scan when there is a re-direct. Could you perhaps introduce a -y flag or similar, which just assumes that I want to follow the re-direction? 

Great tool and keep up the good work!

Thanks.

**Comment by Tuhinshubhra** [comment]
Hi i have added 2 new arguments `--follow-redirect` and `--no-redirect` please try these and let me know if this works for you.

**Comment by smicallef** [comment]
Looks great, thanks!
