### ISSUE TITLE
[SUGGESTION] CMS detction failed!

### ISSUE THREAD

**Issue by diyarit** [Tuhinshubhra/CMSeeK#47]
- CMSeeK Version: 1.1.0
    - Target: http://www.ngoao.gov.iq/
    - Probable CMS: <almubda 1.8>

**Comment by Tuhinshubhra** [comment]
I added detection for Al Mubda, although due to no/less test targets I couldn't get enough detection parameters. Closing issue now feel free to reopen if you have any other suggestions.
