### ISSUE TITLE
SyntaxError: Non-ASCII character

### ISSUE THREAD

**Issue by ahmedtaher1986** [Tuhinshubhra/CMSeeK#5]
Traceback (most recent call last):
  File "cmseek.py", line 9, in <module>
    import cmseekdb.basic as cmseek # All the basic functions
  File "/root/Desktop/CMSeeK/cmseekdb/basic.py", line 67
SyntaxError: Non-ASCII character '\xc3' in file /root/Desktop/CMSeeK/cmseekdb/basic.py on line 67, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by Tuhinshubhra** [comment]
Possibly fixed, could you update your version of CMSeeK, retry and update me if it still exists

**Comment by ahmedtaher1986** [comment]
Same result bro even after updating CMSeeK

**Comment by ahmedtaher1986** [comment]
It worked like a charm. The problem fixed when running the script using python3. thanks

**Comment by Tuhinshubhra** [comment]
Thanks @Snifer, Closing issue now
