### ISSUE TITLE
[Feature request] prestashop detection support

### ISSUE THREAD

**Issue by noraj** [Tuhinshubhra/CMSeeK#50]
Hi, thx for the amazing work
Prestashop detection support https://www.prestashop.com/en would be great

**Comment by Tuhinshubhra** [comment]
I've added parameters for PrestaShop detection if you have any other suggestions feel free to open a new issue. Thank you for improving CMSeeK.

**Comment by noraj** [comment]
@Tuhinshubhra Awesome! I will have to try that.
Also I saw https://prestavc.com/ was able to detect the prestashop version, but I don't know how.

**Comment by Tuhinshubhra** [comment]
Thanks i'll figure out a way to detect prestashop versions, thanks for letting me know.

**Comment by noraj** [comment]
prestavc is able to get the exact version so the version must be disclosed in one file or something.

**Comment by noraj** [comment]
As it is always nice to hear it: you are awesome and your project too, thx for maintaining it :)

**Comment by Tuhinshubhra** [comment]
I know matching the signatures of publicly accessible files is a good way but I kinda have some stuffs going on so yeah sure i can do that but will take some time.

**Comment by Tuhinshubhra** [comment]
Closing the issue for now, I will update once i add prestashop version detection
