### ISSUE TITLE
BigTreeCMS Support

### ISSUE THREAD

**Issue by DrRetsiemsuah** [Tuhinshubhra/CMSeeK#53]
I noticed that BigTreeCMS seems to be unsupported for detection.

**Comment by Tuhinshubhra** [comment]
Hi, thank you for your feedback.
While CMSeeK detects many CMS it certainly doesn't detect all, if you want detection for **BigTreeCMS** please provide me with some targets that uses it, this will help me find the detection parameters.

**Comment by DrRetsiemsuah** [comment]
Hey, sure thing. I tried to figure out some sites via google, these two have it definitely installed:
- http://ngatia.me.ke/site/index.php/
- http://www.dayaciptamandiri.com/cms/site/index.php/
However, I will have a look for some more websites later on.

**Comment by Tuhinshubhra** [comment]
Thank you for the targets i will add bigTreeCMS detection asap!

**Comment by Tuhinshubhra** [comment]
Added detection for BigTree CMS, Thank you for your contribution in making CMSeeK better!
Closing the issue now, feel free to reopen in case something don't work out.
