### ISSUE TITLE
CMSeek showing error

### ISSUE THREAD

**Issue by exrme18** [Tuhinshubhra/CMSeeK#56]
Hey @Tuhinshubhra 

While running cmseek on wp and jomla I am getting an error whereas running the joomscan and wpscan is working fine. 
Error:
```
File "cmseek.py", line 136, in <module>
    core.main_proc(site,cua)
  File "/home/tools/CMSeeK/cmseekdb/core.py", line 132, in main_proc
    result.target(site)
  File "/home/tools/CMSeeK/cmseekdb/result.py", line 12, in target
    print(' \u250f\u2501Target: ' + cmseek.bold + cmseek.red + target + cmseek.cln)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
```

Can you please help me to fix this?
Thanks

**Comment by Tuhinshubhra** [comment]
Could you provide me with the target you're trying to scan?

**Comment by Tuhinshubhra** [comment]
Also the operating system you're using...

**Comment by exrme18** [comment]
Hey @Tuhinshubhra 
OS is Debian 9.
Thanks

**Comment by NANO-Chile** [comment]
Im getting exactly same error with any site I scan (option 1)

Example target: invernaderobanda.cl
OS: Ubuntu 16.04 x64

**Comment by NANO-Chile** [comment]
@Tuhinshubhra any help?

**Comment by ajxchapman** [comment]
Had the same error when running CMSeeK in the default Ubuntu bionic docker image. This appears to be caused by the use of extended Unicode characters in the output printing in `cmseekdb/results.py`.

This can be mitigated by installing `language-pack-en` and exporting the `LANG="en_US.UTF-8"`:
```sh
apt-get install -y language-pack-en
export LANG="en_US.UTF-8"
python3 cmseek.py -u http://www.drupal.com
```

**Comment by Tuhinshubhra** [comment]
Thanks @ajxchapman ... Here's a solution @LayerCorp @exrme18
