### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by securiteinfo** [Tuhinshubhra/CMSeeK#57]
Hello, Using CMSeek 1.1.1, got this error : 

 [+]  CMS Detection And Deep Scan  [+]

[i] Scanning Site: https://n0where.net/
[x] Aborting CMSeek! Couldn't connect to site
    Error: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)>

**Comment by Tuhinshubhra** [comment]
Appears to be working here, anyways i will disable SSL check for the future version.. thank you for the report.
![image](https://user-images.githubusercontent.com/28696468/53893512-593b4d80-4054-11e9-9261-a38b7e42a308.png)
