### ISSUE TITLE
[Feature Request] Batch Mode

### ISSUE THREAD

**Issue by riramar** [Tuhinshubhra/CMSeeK#59]
Thanks for a good tool. How about include in your roadmap a feature to run as batch mode.
With the flag someone could use in their script to run CMSeek and accept all default answer.

**Comment by Tuhinshubhra** [comment]
> python3 cmseek.py -u <target> --random-agent --follow-redirect
You can run this and you won't be prompted for anything... anyways i'll try to add the batch option for functions like brute forcing.. thank you!
