### ISSUE TITLE
Wrong detection result on site canifa.com 

### ISSUE THREAD

**Issue by longtranf** [Tuhinshubhra/CMSeeK#63]
Result: Wordpress, Detection method: Source
Actually it's magento site.

**Comment by Tuhinshubhra** [comment]
Thank you for reporting... I'll fix it ASAP

**Comment by Tuhinshubhra** [comment]
Hi I have added the `--ignore-cms` argument to help avoid false wp detection also some previous fixes were done to detect false positive detection of WordPress. 

try `python3 cmseek.py -v --follow-redirect -u canifa.com --ignore-cms wp`

I'm sorry I couldn't fix the issue sooner. 
Thank you for making CMSeeK better! I will be closing the issue feel free to reopen if anything is not working right!
