### ISSUE TITLE
need hit ENTER after each domain check from list ?

### ISSUE THREAD

**Issue by masterwebsk** [Tuhinshubhra/CMSeeK#64]
Hi, I´m using command 
`python3 cmseek.py -l list.txt --follow-redirect`
but after each domain-check script asking me "Press [ENTER] to continue"

Is some argument to run script for multiple domains just one after another without confirming ? I´m checking many domains..

**Comment by HackAttack420** [comment]
+

**Comment by Tuhinshubhra** [comment]
I'm sorry there's no arguments as of now but i'll add a `--batch` option soon!

**Comment by masterwebsk** [comment]
> I'm sorry there's no arguments as of now but i'll add a `--batch` option soon!

Hi, --batch will be great. Please inform me.
Thanks.

**Comment by Tuhinshubhra** [comment]
Hi I have added the batch mode as requested. Hope it solves your issue.
Closing the thread now, feel free to reopen in case there is something wrong.
Thank you for making CMSeeK better :)
