### ISSUE TITLE
CMS detection failed

### ISSUE THREAD

**Issue by srikug** [Tuhinshubhra/CMSeeK#66]
- CMSeeK Version:1.1.1
- Target: https://www.darkmatter.ae/
- Probable CMS: Umbraco

Please update your CMSeeK. :)

**Comment by Tuhinshubhra** [comment]
Hi, thank you for the issue i will be pushing umbraco detection within an hour or so!

**Comment by Tuhinshubhra** [comment]
Hi I have added Umbraco detection including version detection, although your target's version can not be determined.

![image](https://user-images.githubusercontent.com/28696468/57791846-539c6b00-775b-11e9-9cc1-f44242cb7d1e.png)

Thank you for helping me improve CMSeeK. Feel free to open a new issue for suggesting any more CMS.

**Comment by srikug** [comment]
Thank you. Hope to see further improvements in near future.🙂🙂
