### ISSUE TITLE
scan only choosen CMS

### ISSUE THREAD

**Issue by masterwebsk** [Tuhinshubhra/CMSeeK#67]
Hi, there is argument --ignore-cms - what is good, but useful function can be also some kind of opposite to this. "scan only selected version/s"

PS: thank for --batch (however, its not working with -u, must "reinstall" script from zero)

**Comment by Tuhinshubhra** [comment]
Hi thank you for the suggestion i will add a strict scan mode asap!

Also could you elaborate `however, its not working with -u, must "reinstall" script from zero)`? What's the error/issue

**Comment by masterwebsk** [comment]
> Hi thank you for the suggestion i will add a strict scan mode asap!
> 
> Also could you elaborate `however, its not working with -u, must "reinstall" script from zero)`? What's the error/issue

after update CMSeeK with -u, --batch was not working. Just after remowing and again git clone cmseek was --batch working (try, maybe some kind my fault)

**Comment by Tuhinshubhra** [comment]
Hey @masterwebsk I have added `--strict-cms` argument! Could you try and say if it works as you intended it to?

Do a `git-pull` for now to get the update.

**Comment by masterwebsk** [comment]
Hi, thanks.

Well, it looks working, but:
- it creating result from each domain (half empty - last attachment) and this will conflict with requested function --skip-if-in-results
- found some urls where script stopped working (see attachments 1+2)

I´m running: 
`python3 cmseek.py -l list.txt --follow-redirect --random-agent --batch --strict-cms wp`

![2019-05-17_16-10](https://user-images.githubusercontent.com/34682252/57934213-73e53a80-78bf-11e9-9db1-f1f8c24cb14e.png)
![2019-05-17_16-08](https://user-images.githubusercontent.com/34682252/57934214-73e53a80-78bf-11e9-8755-e8e6093f92f6.png)

![2019-05-17_16-23](https://user-images.githubusercontent.com/34682252/57934501-287f5c00-78c0-11e9-9c2f-b457b2bc14ce.png)

**Comment by Tuhinshubhra** [comment]
Thank you for the update let me check and i'll get back to it.

**Comment by Tuhinshubhra** [comment]
I have fixed the cmseek exiting in between scans problem.. however i am unable to reproduce the result of incomplete result. Try the fix and let me know if it's still an issue.
