### ISSUE TITLE
ignore in Results

### ISSUE THREAD

**Issue by masterwebsk** [Tuhinshubhra/CMSeeK#68]
After some scans I found that there are some CMS or URLS which taking much time. So I deleted them from list.txt and ran batch scan again. But it starts again from first url. Can you add some argument --ignore-if-in-results ?

Thanks

**Comment by Tuhinshubhra** [comment]
Sure, I will add it asap!

**Comment by Tuhinshubhra** [comment]
Hey @masterwebsk I've added `--skip-scanned` argument try it and let me know if it serves your purpose!

**Comment by masterwebsk** [comment]
Hi, it looks working. Just when run very first time after fresh install cant find/create main directory Result and quit with error.
Tried first run without --skip-scanned, and than with --skip-scanned and it looks working. Will test more on days.

Thanks for now.

(what about creating results of all scanned if there is --strict-cms wp ? in this case will --skip-scanned not good idea). Use case: I have 10k domains for example in the list. I want scan first just for WP, then grep results for WP, afterthat will scan for joomla and drupal (or add/update domains list), but with --skip-scanned it will not working...

![2019-05-19_12-31](https://user-images.githubusercontent.com/34682252/57981384-fcd2b200-7a36-11e9-936c-c7f93092998e.png)

**Comment by Tuhinshubhra** [comment]
The latest commit will fix the quitting issue and I don't think the idea of storing strict scan results separely is a good idea as of now, however I might add it in future.

Thank you for helping me improve CMSeeK! I'm closing the issue now but feel free to open a new one for any other improvements or suggestions.
