### ISSUE TITLE
list.txt structure improvement

### ISSUE THREAD

**Issue by masterwebsk** [Tuhinshubhra/CMSeeK#69]
Again after some testing with lot of domains in list (thousands) is problematic to remove some of unwanted urls in nano editor (even new copying from clipboard to new list.txt taking lot time). Can be domains structure be also domain per line? Not just domain,domain,domain,domain.

Thanks :)

**Comment by Tuhinshubhra** [comment]
Try this command to convert newline separation in a file to comma.

`tr '\n' ',' < input.txt > output.txt`
