### ISSUE TITLE
scanner halt with error if empty .json

### ISSUE THREAD

**Issue by masterwebsk** [Tuhinshubhra/CMSeeK#70]
script halt if find empty .json file in Result/domain 

(dont have screenshot, but after removing directory with empty .json, script is running ok)

**Comment by Tuhinshubhra** [comment]
empty json? I will need a little more info..

**Comment by masterwebsk** [comment]
I cant provide bad url for you for now - dont remember which domain was it, and I removed it from the list, so cant reproduce bug. But if it will repeat, I will send you a domain for better reproducing the problem.

**Comment by Tuhinshubhra** [comment]
Never mind got the bug fixed it as well!

**Comment by masterwebsk** [comment]
just one mention (maybe will help more) - I will continue with not updated CMSeeK / the error was even with --skip-scanned

**Comment by Tuhinshubhra** [comment]
@masterwebsk  I'm sorry i didn't understand what you're trying to say.. could you please elaborate?

**Comment by masterwebsk** [comment]
I mean, that --skip-scanned should skip domain/.json if exist. but if there is empty .json it was not skipping and continuing.

**Comment by Tuhinshubhra** [comment]
well this was the indented design!
