### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by mastercho** [Tuhinshubhra/CMSeeK#71]
Love the script and good work!

Saw in WP bruteforce you do in wp-login way. Which is easy to detect and block. You must try to brute XMLRPC method, its faster and hard to block from WAF. 

Maybe we can add an option to resolve hosting for all domains on IP and go and check through all of them :)

**Comment by Tuhinshubhra** [comment]
Thank you for the feedback, I will add the WordPress xmlrpc brute force module asap. 

As of the other idea I'm not sure about that! maybe you can create a PR?

**Comment by Tuhinshubhra** [comment]
Hi i have added the bruteforce module, give it a try and do let me know if anything needs to be changed. Thank you for helping me make CMSeeK better!

**Comment by Tuhinshubhra** [comment]
Closing the issue for now.. feel free to reopen the issue if something goes wrong!
