### ISSUE TITLE
HOW to fix it？

### ISSUE THREAD

**Issue by safebaseline** [Tuhinshubhra/CMSeeK#72]
targetlist：
![图片](https://user-images.githubusercontent.com/38883009/58602718-7f256680-82c0-11e9-8456-0bc4ee8852a0.png)
running：
![图片](https://user-images.githubusercontent.com/38883009/58602788-bc89f400-82c0-11e9-83ee-7449c89720df.png)

**Comment by safebaseline** [comment]
cmd:python3 cmseek.py -l ./target.txt

 [+]  CMS Detection And Deep Scan  [+] 

Traceback (most recent call last):
  File "cmseek.py", line 126, in <module>
    target = cmseek.process_url(s)
  File "/root/CMSeeK/cmseekdb/basic.py", line 193, in process_url
    init_result_dir(target)
  File "/root/CMSeeK/cmseekdb/basic.py", line 237, in init_result_dir
    os.makedirs(result_dir)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '/root/CMSeeK/Result/cc.xxx.comwww.xxx.comvideo.xxx.compay.xxx.comhi.xxxx.comoa.xxx.commusic.xxxx.c

**Comment by Tuhinshubhra** [comment]
separate the file list by comma "`,`" instead of newline.

try this command `tr '\n' ',' < input.txt > output.txt`

**Comment by safebaseline** [comment]
how to skip it?
![图片](https://user-images.githubusercontent.com/38883009/58603829-cdd4ff80-82c4-11e9-8e2f-5d210d5639fe.png)

**Comment by safebaseline** [comment]
Don't show the message "Press [ENTER] to continue",just continue.

**Comment by Tuhinshubhra** [comment]
use `--batch`
