### ISSUE TITLE
Microsoft ASP.NET detection failed

### ISSUE THREAD

**Issue by Nzaime38** [Tuhinshubhra/CMSeeK#75]
Hi and thank you for this amazing tool. 
I tried to detect a website CMS and it failed. I did more investigation and i found out that the CMS was Microsoft ASP.NET. I don't know if it's usefull to add this one but i wanted to tell you about this issue. 
Have a nice day !

**Comment by Tuhinshubhra** [comment]
ASP.NET is not really a CMS so i'll be closing the issue.
