### ISSUE TITLE
Title: [SUGGESTION] CMS detction failed!

### ISSUE THREAD

**Issue by sher1** [Tuhinshubhra/CMSeeK#77]
Content:
    - CMSeeK Version: 1.1.2
    - Target: https://news.byu.edu/
    - Probable CMS: Brightspot

I know this one is correct. I have worked on the site

**Comment by Tuhinshubhra** [comment]
Hi I have added detection for Brightspot CMS. Thank you for helping me improve CMSeeK. Don't hesitate to open a new issues if something is not working, closing this issue!
