### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by mr007guy** [Tuhinshubhra/CMSeeK#78]
[i] updating CMSeeK result index...
[x] Result directory does not exist!
There was an error while creating result index! some features might not work as intended. Press [enter] to continue

Hi i get this when running the script.

**Comment by Tuhinshubhra** [comment]
For now just press enter.. i am working on this issue

**Comment by mr007guy** [comment]
No problem bro :) thank you so much for the tool :) other then twitter is there another way to contact you?

**Comment by Tuhinshubhra** [comment]
You're welcome! Well you can mail me @ contactr3d@protonmail.com
