### ISSUE TITLE
Force Close

### ISSUE THREAD

**Issue by aikusuma** [Tuhinshubhra/CMSeeK#8]
> Trying deepscaan
> Scaning Site
> User Agent
Force close

> Trying Bruteforce CMS
> Press 3
Force close

Sorry for no proff but this is what happend to me.
Any advice?

**Comment by Tuhinshubhra** [comment]
i will need a little more info,
1. Target you were scanning
2. Copy and paste the exact error

**Comment by Tuhinshubhra** [comment]
Closing issue, feel free to open with the above mentioned details.
