### ISSUE TITLE
Drupal detection fails when domain is included in src

### ISSUE THREAD

**Issue by nmfm** [Tuhinshubhra/CMSeeK#80]
When it comes to detecting drupal, CMSeeK is expecting the `drupal.js` file to be included[
exactly like](https://github.com/Tuhinshubhra/CMSeeK/blob/ddd0e3f71b12a456bf898645ec2219c7f8f33013/cmseekdb/sc.py#L28) 

```
src="/misc/drupal.js"
```

However, some sites put the full URL not just the path, on the `src` attribute, and may add a suffix, probably for versioning.

For instance:

```
<script type="text/javascript" src="https://mcdonalds.com.au/misc/drupal.js?pww3o6"></script>
```

In these cases detection fails.

Two possible solutions would be:

a. use a simpler expression like for Joomla ( "css/joomla.css:-joom" )
b. use a more complex expression that handles the domain and protocol and a suffix

**Comment by Tuhinshubhra** [comment]
hey @nmfm do create a PR ;)
