### ISSUE TITLE
WPVulnDB APIv2 Deprecation October 1st

### ISSUE THREAD

**Issue by ethicalhack3r** [Tuhinshubhra/CMSeeK#81]
Hi,

You are currently using WPVulnDB APIv2, which is due to be deprecated on October 1st, 2019.

https://github.com/mainwp/mainwp-child/search?q=wpvulndb&unscoped_q=wpvulndb

Please update your code to use WPVulnDB APIv3 before October 1st, which will require your users to register an account on wpvulndb.com and configure an API token that will give them 50 free API requests per day. Anything more than 50 API requests per day will require purchasing paid API usage.

For further details please see:

https://blog.wpscan.org/wpvulndb/2019/07/05/wpvulndb-apiv2-deprecation.html

Thanks,
Ryan

**Comment by Tuhinshubhra** [comment]
Thanks Ryan for letting me know. I'll migrate to the new version.
