### ISSUE TITLE
not need (non-WP) results

### ISSUE THREAD

**Issue by masterwebsk** [Tuhinshubhra/CMSeeK#85]
Hello,

im using command `python3 cmseek.py -l output.txt --follow-redirect --random-agent --batch --strict-cms wp --skip-scanned` 

Need just WP sites (for this moment), but in Results are all domains from output.txt. In real situation there are 2k domains in txt and in Results directory but real there is just 10-15% of them WP sites.

some argument? :)

**Comment by Tuhinshubhra** [comment]
you can simply grep the cms.json and look for `"cms_id": "wp"`
