### ISSUE TITLE
HTTPConnectionPool Error

### ISSUE THREAD

**Issue by teodem** [Tuhinshubhra/CMSeeK#88]
By running CMSeek i get this error: 

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //target (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f10e72d7190>: Failed to establish a new connection: [Errno -2] Name or service not known',))`

do you any idea about the cause?

Thank you very much!

**Comment by Tuhinshubhra** [comment]
It's an issue with your connection not cmseek as far as i can tell. 

Closing the issue for now.
