### ISSUE TITLE
CMS Detection Failed

### ISSUE THREAD

**Issue by rweed1** [Tuhinshubhra/CMSeeK#91]
Weebly - Doesn't seem to get detected

EKM Powershop  - Doesn't seem to get detected

GoDaddy Website Builder   - Doesn't seem to get detected

**Comment by Tuhinshubhra** [comment]
Hi @rweed1, 
I have added detection for all the CMSs.
Thank you for helping me make CMSeeK better!
Closing issue now, feel free to open a new issue for other suggestions.
