### ISSUE TITLE
CMS detection failed!

### ISSUE THREAD

**Issue by mickyyman** [Tuhinshubhra/CMSeeK#93]
- CMSeeK Version: 1.1.2
 - Target: http://www.gimnaz53.ru/
 - Probable CMS: Amiro.CMS
 - Vendor: https://www.amiro.ru/

You can also detect the CMS version by looking at the included css files.
ie. http://www.gimnaz53.ru/_mod_files/_css/home.css?_cv=5.10.0.7

**Comment by Tuhinshubhra** [comment]
Thank you for reporting, I will add support ASAP.

**Comment by Tuhinshubhra** [comment]
Hi, I have added detection for Amiro.CMS incl. version detection.
Thank you for helping me make CMSeeK better!
Closing issue now, feel free to open new issue for any other suggestions or improvements.
