### ISSUE TITLE
Joomla JSON

### ISSUE THREAD

**Issue by zionbigorna** [Tuhinshubhra/CMSeeK#94]
If you try to scan joomla cms and if it finds vulns it wont output to the json results file

**Comment by Tuhinshubhra** [comment]
Thank you for reporting the issue, I will look into it and fix it ASAP.

**Comment by Tuhinshubhra** [comment]
@zionbigorna Thank you for reporting the issue, I have pushed a proper fix for the bug.
Now CMSeeK should log all core vulns of joomla.

Closing issue now.
