### ISSUE TITLE
ZenCart CMS detection failed

### ISSUE THREAD

**Issue by MsJamie** [Tuhinshubhra/CMSeeK#95]
- CMSeeK Version: 1.1.2
    - Target: https://www.continentalbeadsuppliers.com/
    - CMS: ZenCart - https://www.zen-cart.com/

Meta tag: 
<meta name="generator" content="shopping cart program by Zen Cart&reg;, http://www.zen-cart.com eCommerce" />

Version is 1.5.4 but cannot be determined from the website page that I can find. Only the CMS name

**Comment by Tuhinshubhra** [comment]
@MsJamie Thank you for the suggestion, I've added detection for ZenCart.
Closing the issue now.
