### ISSUE TITLE
IPO CMS detection failed!

### ISSUE THREAD

**Issue by multiflexi** [Tuhinshubhra/CMSeeK#96]
- CMSeeK Version: 1.1.2
    - Target: https://www.gjr.cz/
    - Probable CMS: IPO - https://translate.google.com/translate?sl=cs&tl=en&u=https%3A%2F%2Fwww.antee.cz%2Fredakcni-system-ipo

**Comment by Tuhinshubhra** [comment]
Hey @multiflexi I can't seem to find enough targets to determine detection parameters.
If you happen to have a list of websites that use IPO feel free to share that with me.

**Comment by multiflexi** [comment]
[Here](https://gist.github.com/multiflexi/83920acf3c63245c1d0c62d2d65d168d) is the list of some websites using IPO I found.

**Comment by Tuhinshubhra** [comment]
@multiflexi Thank you for the list. I'm working on it.

**Comment by Tuhinshubhra** [comment]
Hey @multiflexi, Thank you for your suggestion, I have added detection for IPO CMS in the latest push.

Closing issue now, feel free to open a new one for other suggestions/improvements.
