### ISSUE TITLE
[SUGGESTION] CMS detction failed!

### ISSUE THREAD

**Issue by elias2k17** [Tuhinshubhra/CMSeeK#98]
- CMSeeK Version: 1.1.2
    - Target: https://www.mundiario.com/
    - Probable CMS: OpenNemas

Check original site or check result of this service https://whatcms.org/?s=www.mundiario.com

**Comment by Tuhinshubhra** [comment]
Hey @elias2k17 how did you find out the CMS version?

**Comment by Tuhinshubhra** [comment]
I have added detection for the CMS, I'll keep the issue open for now until I discover a method to find the CMS version.

**Comment by Tuhinshubhra** [comment]
@elias2k17 Thank you for the suggestion, I have now added support for OpenNemas.
Closing issue.
