### ISSUE TITLE
Add new command-line switches to manipulate version detection & deep scan

### ISSUE THREAD

**Issue by elias2k17** [Tuhinshubhra/CMSeeK#99]
Hi there!
Many thanks for your awesome tool!
Could you please add two new command-line switches to control vd and deeps parameters.
Sometimes we need to scan about 12k domains and there is no need to run deep scan/version detection. This time I've disabled vd/deeps parameters for all cms type inside cmss.py file. But it would be convenient to have such  command-line switches.
Thanks in advance!

**Comment by Tuhinshubhra** [comment]
Hi @elias2k17 
Thank you for the suggestion, I'll try to add this feature soon.

**Comment by Tuhinshubhra** [comment]
Hey @elias2k17 I've added a new argument called `--light-scan` which will ignore deep scan and only determine the CMS and version.

**Comment by Tuhinshubhra** [comment]
I've also added, `--only-cms`, `-o` argument, that only detects CMS and ignores version scan or deep scan.

**Comment by Tuhinshubhra** [comment]
I'll close the issue now, if you have any other issues feel free to open a new issue.
Thank you for helping me make CMSeeK better.
